// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDigK7gI934H8rXbpvWiD_jCp0uX1xwbSg',
    appId: '1:944325399193:web:0b56de854ceb01219d1e08',
    messagingSenderId: '944325399193',
    projectId: 'endsem-ec83d',
    authDomain: 'endsem-ec83d.firebaseapp.com',
    storageBucket: 'endsem-ec83d.firebasestorage.app',
    measurementId: 'G-61L2NEJCQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY7bRpcwlw9q6Ic4AmIwF0PFJAj6giYRU',
    appId: '1:944325399193:android:5c8b226fd3fcceba9d1e08',
    messagingSenderId: '944325399193',
    projectId: 'endsem-ec83d',
    storageBucket: 'endsem-ec83d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaf4Spq3jGEBhbYPj74_t6to0GEmODwd0',
    appId: '1:944325399193:ios:5acf986f1d67f4c99d1e08',
    messagingSenderId: '944325399193',
    projectId: 'endsem-ec83d',
    storageBucket: 'endsem-ec83d.firebasestorage.app',
    iosBundleId: 'com.example.cse23523',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaf4Spq3jGEBhbYPj74_t6to0GEmODwd0',
    appId: '1:944325399193:ios:5acf986f1d67f4c99d1e08',
    messagingSenderId: '944325399193',
    projectId: 'endsem-ec83d',
    storageBucket: 'endsem-ec83d.firebasestorage.app',
    iosBundleId: 'com.example.cse23523',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDigK7gI934H8rXbpvWiD_jCp0uX1xwbSg',
    appId: '1:944325399193:web:f2fa4652d78791439d1e08',
    messagingSenderId: '944325399193',
    projectId: 'endsem-ec83d',
    authDomain: 'endsem-ec83d.firebaseapp.com',
    storageBucket: 'endsem-ec83d.firebasestorage.app',
    measurementId: 'G-YJ6X4X04ZP',
  );

}